updating docs from 'useSignInCheck' to 'useSigninCheck'
FirebaseExtended/reactfire pull request #505
Opened 2022-02-05 23:52 UTC by thomasmburke

Ran into import errors when following the docs because of this subtle lowercase `i`.

I think overall it would be worth having this camel case exception be consistent with `signInCheckResult`, but not worth introducing a breaking change in my opinion, so just looking to update the docs and references in this repo.

2022-05-16 21:39 UTC, jhuleatt approved these changes

2022-05-16 21:40 UTC, jhuleatt commented
Thanks @thomasmburke!

2022-05-16 21:41 UTC, jhuleatt requested changes
Thanks! Can you please update in the source as well so that these changes persist next time the docs are generated?

https://github.com/FirebaseExtended/reactfire/blob/eb1428b9e7923a898cff73ca4725c012b4074bae/src/auth.tsx#L204

https://github.com/FirebaseExtended/reactfire/blob/eb1428b9e7923a898cff73ca4725c012b4074bae/src/auth.tsx#L241

2022-08-17 18:44 UTC, jhuleatt commented
fixed in this commit: https://github.com/FirebaseExtended/reactfire/commit/414201e88bd6f6701998993f6203e4d49773147b

2022-08-17 18:44 UTC, closed without merging

2022-08-17 20:57 UTC, thomasmburke commented
Sorry for missing this!